### ISSUE TITLE
Do you have a script which allows that when the car has more energy soon and it is in auto pilot that it makes a sound effect and that it drives it I used the nearest Super Charger?

### ISSUE THREAD

**Issue by flyzar73** [Playlolly/playlolly_tesla_functions#4]
Do you have a script which allows that when the car has more energy soon and it is in auto pilot that it makes a sound effect and that it drives it I used the nearest Super Charger?

**Comment by Boostvolt** [comment]
I will take a closer look and implement it if possible.

**Comment by flyzar73** [comment]
ok

**Comment by flyzar73** [comment]
if it is necessary the sound noise is not obliged but it will be better

**Comment by boostvolt** [comment]
I have now implemented the following sounds:
- Autopilot on / off / reached
- Marker on / off
- Crash avoidance on / off / detection
- Tesla Dance 

For this you have to download the new files in the master branch as well as [playlolly_sounds](https://github.com/playlolly/playlolly_sounds).
