### ISSUE TITLE
BUG SuperCharger

### ISSUE THREAD

**Issue by flyzar73** [Playlolly/playlolly_tesla_functions#5]
Supercharging them does not work when I fill my car it comes back with the same amount of energy as before

**Comment by EinfachMarcel** [comment]
do you using LegacyFuel?

**Comment by flyzar73** [comment]
wait I don't remember

**Comment by flyzar73** [comment]
yes

**Comment by Boostvolt** [comment]
You have to disable LegacyFuel. Otherwise it won't work.

**Comment by EinfachMarcel** [comment]
you can exclude Vehicles by Spawname from the Script then the Supercharger will work

**Comment by flyzar73** [comment]
ok

**Comment by EinfachMarcel** [comment]
> You have to disable LegacyFuel. Otherwise it won't work.

you can exclude Vehicles by Spawname from the Script then the Supercharger will work

**Comment by EinfachMarcel** [comment]
```
Config.Blacklist = {
	--"Adder",
	--276773164
}
```

**Comment by flyzar73** [comment]
thank you i saw

**Comment by flyzar73** [comment]
its done
